[package]
name = "anagramme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
unicode-normalization = "0.1.19"
patricia_tree = "0.3.1"
